### ISSUE TITLE
Mod Manager Crashing on Startup

### ISSUE THREAD

**Issue by zyou850** [Kaedrin/warhammer-mod-manager#103]
The issue here might be a long one as I'm going to try to be as detailed as possible. 

I have a new computer that I installed Warhammer 2 onto last month. I hadn't played it at that time, but I have launched it from Steam. I installed the mod manager, the 1.9 version, and it will first tell me that user preferences are being reset. I click ok, and then the manager comes up. But it is 'not responding'. It does this for a moment, then closes with no error message whatsoever. 

I attempted to use the previous version of the manager. It does the exact same thing. I've closed and reclosed steam between changing versions as well. I've also gone back to even older versions of the manager. The only one that even kind of works is 1.4. Which the problem there is that it doesn't load all of my mods at that point. And the game typically crashes. Though I haven't extensively tested that part. 

At this point I have switched versions of the manager multiple times. I've deleted every file associated with it that I could. I've validated my game. I've uninstalled the game, and reinstalled it. I've run the exe as admin as well. I also disabled realtime protection in Windows and allowed both warhammer 2 and the mod manager through the firewall. The manager still does not load. 

Strangely as well, version 1.8.15 was working on my laptop yesterday. But has abruptly stopped working for seemingly no reason.

**Comment by Umiiee** [comment]
I'm having the same thing, starts up then stops responding and closes, I'm running it as administrator and tried turning off antivirus and firewall

**Comment by Dragon-32** [comment]
Same here. 

Application error:
```
Faulting application name: Warhammer2MM.exe, version: 1.0.0.0, time stamp: 0x643d22b2
Faulting module name: steamclient.dll, version: 8.9.11.89, time stamp: 0x6476603a
Exception code: 0xc0000005
Fault offset: 0x00beb8be
Faulting process ID: 0x0x4A4C
Faulting application start time: 0x0x1D99C6C68379EB7
Faulting application path: C:\Programs\Total War Mod Manager\Warhammer2MM.exe
Faulting module path: C:\Program Files (x86)\Steam\steamclient.dll
Report ID: a94fbdbc-849d-4997-873f-50922e23c989
Faulting package full name: 
Faulting package-relative application ID: 
```
.NET Runtime error:
```
Application: Warhammer2MM.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Steamworks.NativeMethods.ISteamUGC_GetQueryUGCResult(IntPtr, Steamworks.UGCQueryHandle_t, UInt32, Steamworks.SteamUGCDetails_t ByRef)
   at KMM.Steam.ItemDetailsRequest.WaitForResult()
   at KMM.Steam.Workshop.GetDetails(UInt64)
   at Warhammer2MM.FormMain+<>c__DisplayClass55_0.<HandleFullSteamData2>b__0(Steamworks.PublishedFileId_t)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass30_0`2[[Steamworks.PublishedFileId_t, Steamworks.NET, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ForEachWorker>b__0(Int32)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
Looks like it's trying to do something not allowed by Steam

[Edit:
Exited and re-started the Steam client, re-started KMM and waited. UI eventually populated with games and mods. So, if anyone else reads this: re-start Steam and be more patient than me.]

**Comment by MrPeters93** [comment]
Yeah, the mod manager takes forever to start up with a bunch of large mods.
