### ISSUE TITLE
"Illegal characters in path"

### ISSUE THREAD

**Issue by lavaslime301** [Kaedrin/warhammer-mod-manager#56]
When i try to open the launcher i get a .NET Framework window with this text:

Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you Quit, the application will close immediately.

Illegal characters in path

clicking continue leaves the launcher open, but it's not detecting any mods and launches vanilla game. Trying to detect mods makes the window popup again.

There's also a "details" tab. It contains this text:

System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at PackFileManager.PackFileCodec.Open(String packFullPath)
   at Warhammer2MM.FormMain.<>c__DisplayClass47_0.<LoadPackFiles>b__0(String file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object
<p0>)

and paths to the launcher and several .NET Framework .dll files.
Will post it if it's necessary.

**Comment by lavaslime301** [comment]
Fixed in 1.8.10. Not entirely sure how, but i'm not about to question it.
