### ISSUE TITLE
Length cannot be less than zero!

### ISSUE THREAD

**Issue by TheAnonymous06** [Kaedrin/warhammer-mod-manager#87]
Hi!When I run Kaedrin Mod Manager, it gives the error "Length cannot be less than zero". When I click "Continue", it opens, but the mods do not appear and the manager does not fit the screen completely (launch button on the bottom right is not visible) what should I do please help!!

**Comment by jeff0102** [comment]
hi, you find any solution?

**Comment by Keltnir** [comment]
Same error. Release version 1.9.0

System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   in System.String.Substring(Int32 startIndex, Int32 length)
   in Warhammer2MM.FormMain.HandleContentFolder() in D:\Code\Repo\Kaedrin Mod Manager\TWModManagerv1.8.3\TWModManager\TWModManager\FormMain.cs:line 975
   in Warhammer2MM.FormMain.LoadPackFiles() in D:\Code\Repo\Kaedrin Mod Manager\TWModManagerv1.8.3\TWModManager\TWModManager\FormMain.cs:line 1459
   in Warhammer2MM.FormMain.FormMain_Shown(Object sender, EventArgs e) in D:\Code\Repo\Kaedrin Mod Manager\TWModManagerv1.8.3\TWModManager\TWModManager\FormMain.cs:line 2551
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

Loaded assemblies
mscorlib
    Build version: 4.0.0.0
    Win32 version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Warhammer2MM
    Build version: 1.0.0.0
    Win32 version: 1.0.0.0
    CodeBase: file:///C:/Users/Win10_Game_OS/Downloads/TotalWarModManager/Warhammer2MM.exe
----------------------------------------
System.Windows.Forms
    Build version: 4.0.0.0
    Win32 version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Build version: 4.0.0.0
    Win32 version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Build version: 4.0.0.0
    Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Steamworks.NET
    Build version: 15.0.0.0
    Win32 version: 15.0.0
    CodeBase: file:///C:/Users/*name*/Downloads/TotalWarModManager/Steamworks.NET.DLL
----------------------------------------
System.Xml
    Build version: 4.0.0.0
    Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Build version: 4.0.0.0
    Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Build version: 4.0.0.0
    Win32 version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
mscorlib.resources
    Build version: 4.0.0.0
    Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Build version: 4.0.0.0
    Win32 version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
